set -g default-terminal "xterm-256color"
set -ga terminal-overrides "xterm-256color"

unbind C-b
set -g prefix C-f

unbind r
bind-key r source-file ~/.config/tmux/tmux.conf

bind-key v split-window -h -c "#{pane_current_path}"
bind-key s split-window -v -c "#{pane_current_path}"

bind-key S choose-session
bind-key X kill-session

unbind '"'
unbind %

# tmux-sessionizer
bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"

# toogle last window by hitting again C-f
bind-key C-f last-window

set -g base-index 1
set-window-option -g pane-base-index 1

set -g mouse on

# focus events enabled for terminals that support them
set -g focus-events on

# Set title
set -g set-titles on
set -g set-titles-string "#T"

# Equally resize all panes
bind-key = select-layout even-horizontal
bind-key | select-layout even-vertical

# double space to maximize pane
bind C-Space resize-pane -Z
bind -n C-Right next-window
bind -n C-Left previous-window

# swap windows
bind-key Left swap-window -t -1
bind-key Right swap-window -t +1

# Resize panes
bind-key J resize-pane -D 10
bind-key K resize-pane -U 10
bind-key H resize-pane -L 10
bind-key L resize-pane -R 10

# Select panes
# NOTE(arslan): See to prevent cycling https://github.com/tmux/tmux/issues/1158
bind-key j select-pane -D
bind-key k select-pane -U
bind-key h select-pane -L
bind-key l select-pane -R

set-option -g status-interval 5
# Rename current window: ","
set-option -g automatic-rename on 
set-option -g automatic-rename-format '#{b:pane_current_path}'
# set-option -g default-shell /usr/bin/fish
#
# set -g default-shell /bin/sh
set -g default-command fish

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'wfxr/tmux-power'

set -g @tmux_power_theme '#fce566'

run "~/.tmux/plugins/tpm/tpm"

# Disable confirm before killing
bind-key x kill-pane

# import
if-shell "uname -s | grep -q Darwin" "source ~/.config/tmux/macos.conf"

source ~/.config/tmux/utility.conf
