hyprctl hyprsunset temperature 2500
hyprctl hyprsunset identity

hyprctl hyprsunset gamma 50
hyprctl hyprsunset gamma +10

hyprctl hyprsunset reset
hyprctl hyprsunset reset temperature
hyprctl hyprsunset reset gamma
hyprctl hyprsunset reset identity

hyprctl hyprsunset profile
