background {
    monitor =
    # path = /usr/share/backgrounds/monokai_wallpaper.png   # Use same path as SDDM
    color = rgba(39, 40, 34, 1.0)
    blur_passes = 2 # 0 for crystal clear, 2 for "glass" effect
}

input-field {
    monitor =
    size = 230, 50
    outline_thickness = 3
    rounding = 0
    border_radius = 0
    dots_size = 0.33
    dots_spacing = 0.15
    outer_color = rgb(166, 226, 46) # Monokai Green
    inner_color = rgb(39, 40, 34)   # Monokai Grey
    font_color = rgb(248, 248, 242)
    fade_on_empty = true
    placeholder_text = <i>󰌌  $LAYOUT | Password...</i>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME12
    color = rgb(248, 248, 242)
    font_size = 64
    font_family = JetBrains Mono Nerd Font # Consistent with your terminal
    position = 0, 80
    halign = center
    valign = center
}
