#!/usr/bin/env bash

sinks=($(pactl list short sinks | awk '{print $2}'))

current_sink=$(pactl get-default-sink)

next_sink=""

for i in "${!sinks[@]}"; do
    if [[ "${sinks[$i]}" == "${current_sink}" ]]; then
        next_index=$(((i + 1) % ${#sinks[@]}))
        next_sink="${sinks[$next_index]}"
        break
    fi
done

pactl set-default-sink "$next_sink"

device_desc=$(pactl list sinks | grep -A 50 "Name: $next_sink" | grep "Description:" | cut -d: -f2- | xargs)

notify-send -h string:x-canonical-private-synchronous:audio-switch \
    -u low \
    -i audio-headphones \
    "Audio Output" \
    "$device_desc"
